/* Auto-generated by scripts/generateLocaleStubs.mjs. Do not edit manually. */
import type { Locale } from '../types';

export type DictionaryName =
  | 'ui'
  | 'events'
  | 'social'
  | 'notifications'
  | 'extras'
  | 'stages'
  | 'rebirth'
  | 'eventGenerator'
  | 'settings';

import en_ui from './en/ui.json';
import en_events from './en/events.json';
import en_social from './en/social.json';
import en_notifications from './en/notifications.json';
import en_extras from './en/extras.json';
import en_stages from './en/stages.json';
import en_rebirth from './en/rebirth.json';
import en_eventGenerator from './en/eventGenerator.json';
import en_settings from './en/settings.json';
import vi_ui from './vi/ui.json';
import vi_events from './vi/events.json';
import vi_social from './vi/social.json';
import vi_notifications from './vi/notifications.json';
import vi_extras from './vi/extras.json';
import vi_stages from './vi/stages.json';
import vi_rebirth from './vi/rebirth.json';
import vi_eventGenerator from './vi/eventGenerator.json';
import vi_settings from './vi/settings.json';
import id_ui from './id/ui.json';
import id_events from './id/events.json';
import id_social from './id/social.json';
import id_notifications from './id/notifications.json';
import id_extras from './id/extras.json';
import id_stages from './id/stages.json';
import id_rebirth from './id/rebirth.json';
import id_eventGenerator from './id/eventGenerator.json';
import id_settings from './id/settings.json';
import es_ui from './es/ui.json';
import es_events from './es/events.json';
import es_social from './es/social.json';
import es_notifications from './es/notifications.json';
import es_extras from './es/extras.json';
import es_stages from './es/stages.json';
import es_rebirth from './es/rebirth.json';
import es_eventGenerator from './es/eventGenerator.json';
import es_settings from './es/settings.json';
import it_ui from './it/ui.json';
import it_events from './it/events.json';
import it_social from './it/social.json';
import it_notifications from './it/notifications.json';
import it_extras from './it/extras.json';
import it_stages from './it/stages.json';
import it_rebirth from './it/rebirth.json';
import it_eventGenerator from './it/eventGenerator.json';
import it_settings from './it/settings.json';
import kk_ui from './kk/ui.json';
import kk_events from './kk/events.json';
import kk_social from './kk/social.json';
import kk_notifications from './kk/notifications.json';
import kk_extras from './kk/extras.json';
import kk_stages from './kk/stages.json';
import kk_rebirth from './kk/rebirth.json';
import kk_eventGenerator from './kk/eventGenerator.json';
import kk_settings from './kk/settings.json';
import zh_Hans_ui from './zh-Hans/ui.json';
import zh_Hans_events from './zh-Hans/events.json';
import zh_Hans_social from './zh-Hans/social.json';
import zh_Hans_notifications from './zh-Hans/notifications.json';
import zh_Hans_extras from './zh-Hans/extras.json';
import zh_Hans_stages from './zh-Hans/stages.json';
import zh_Hans_rebirth from './zh-Hans/rebirth.json';
import zh_Hans_eventGenerator from './zh-Hans/eventGenerator.json';
import zh_Hans_settings from './zh-Hans/settings.json';
import zh_Hant_ui from './zh-Hant/ui.json';
import zh_Hant_events from './zh-Hant/events.json';
import zh_Hant_social from './zh-Hant/social.json';
import zh_Hant_notifications from './zh-Hant/notifications.json';
import zh_Hant_extras from './zh-Hant/extras.json';
import zh_Hant_stages from './zh-Hant/stages.json';
import zh_Hant_rebirth from './zh-Hant/rebirth.json';
import zh_Hant_eventGenerator from './zh-Hant/eventGenerator.json';
import zh_Hant_settings from './zh-Hant/settings.json';
import ko_ui from './ko/ui.json';
import ko_events from './ko/events.json';
import ko_social from './ko/social.json';
import ko_notifications from './ko/notifications.json';
import ko_extras from './ko/extras.json';
import ko_stages from './ko/stages.json';
import ko_rebirth from './ko/rebirth.json';
import ko_eventGenerator from './ko/eventGenerator.json';
import ko_settings from './ko/settings.json';
import ms_ui from './ms/ui.json';
import ms_events from './ms/events.json';
import ms_social from './ms/social.json';
import ms_notifications from './ms/notifications.json';
import ms_extras from './ms/extras.json';
import ms_stages from './ms/stages.json';
import ms_rebirth from './ms/rebirth.json';
import ms_eventGenerator from './ms/eventGenerator.json';
import ms_settings from './ms/settings.json';
import de_ui from './de/ui.json';
import de_events from './de/events.json';
import de_social from './de/social.json';
import de_notifications from './de/notifications.json';
import de_extras from './de/extras.json';
import de_stages from './de/stages.json';
import de_rebirth from './de/rebirth.json';
import de_eventGenerator from './de/eventGenerator.json';
import de_settings from './de/settings.json';
import pl_ui from './pl/ui.json';
import pl_events from './pl/events.json';
import pl_social from './pl/social.json';
import pl_notifications from './pl/notifications.json';
import pl_extras from './pl/extras.json';
import pl_stages from './pl/stages.json';
import pl_rebirth from './pl/rebirth.json';
import pl_eventGenerator from './pl/eventGenerator.json';
import pl_settings from './pl/settings.json';
import pt_ui from './pt/ui.json';
import pt_events from './pt/events.json';
import pt_social from './pt/social.json';
import pt_notifications from './pt/notifications.json';
import pt_extras from './pt/extras.json';
import pt_stages from './pt/stages.json';
import pt_rebirth from './pt/rebirth.json';
import pt_eventGenerator from './pt/eventGenerator.json';
import pt_settings from './pt/settings.json';
import ro_ui from './ro/ui.json';
import ro_events from './ro/events.json';
import ro_social from './ro/social.json';
import ro_notifications from './ro/notifications.json';
import ro_extras from './ro/extras.json';
import ro_stages from './ro/stages.json';
import ro_rebirth from './ro/rebirth.json';
import ro_eventGenerator from './ro/eventGenerator.json';
import ro_settings from './ro/settings.json';
import ru_ui from './ru/ui.json';
import ru_events from './ru/events.json';
import ru_social from './ru/social.json';
import ru_notifications from './ru/notifications.json';
import ru_extras from './ru/extras.json';
import ru_stages from './ru/stages.json';
import ru_rebirth from './ru/rebirth.json';
import ru_eventGenerator from './ru/eventGenerator.json';
import ru_settings from './ru/settings.json';
import sw_ui from './sw/ui.json';
import sw_events from './sw/events.json';
import sw_social from './sw/social.json';
import sw_notifications from './sw/notifications.json';
import sw_extras from './sw/extras.json';
import sw_stages from './sw/stages.json';
import sw_rebirth from './sw/rebirth.json';
import sw_eventGenerator from './sw/eventGenerator.json';
import sw_settings from './sw/settings.json';
import th_ui from './th/ui.json';
import th_events from './th/events.json';
import th_social from './th/social.json';
import th_notifications from './th/notifications.json';
import th_extras from './th/extras.json';
import th_stages from './th/stages.json';
import th_rebirth from './th/rebirth.json';
import th_eventGenerator from './th/eventGenerator.json';
import th_settings from './th/settings.json';
import tr_ui from './tr/ui.json';
import tr_events from './tr/events.json';
import tr_social from './tr/social.json';
import tr_notifications from './tr/notifications.json';
import tr_extras from './tr/extras.json';
import tr_stages from './tr/stages.json';
import tr_rebirth from './tr/rebirth.json';
import tr_eventGenerator from './tr/eventGenerator.json';
import tr_settings from './tr/settings.json';
import fil_ui from './fil/ui.json';
import fil_events from './fil/events.json';
import fil_social from './fil/social.json';
import fil_notifications from './fil/notifications.json';
import fil_extras from './fil/extras.json';
import fil_stages from './fil/stages.json';
import fil_rebirth from './fil/rebirth.json';
import fil_eventGenerator from './fil/eventGenerator.json';
import fil_settings from './fil/settings.json';
import fr_ui from './fr/ui.json';
import fr_events from './fr/events.json';
import fr_social from './fr/social.json';
import fr_notifications from './fr/notifications.json';
import fr_extras from './fr/extras.json';
import fr_stages from './fr/stages.json';
import fr_rebirth from './fr/rebirth.json';
import fr_eventGenerator from './fr/eventGenerator.json';
import fr_settings from './fr/settings.json';
import hi_ui from './hi/ui.json';
import hi_events from './hi/events.json';
import hi_social from './hi/social.json';
import hi_notifications from './hi/notifications.json';
import hi_extras from './hi/extras.json';
import hi_stages from './hi/stages.json';
import hi_rebirth from './hi/rebirth.json';
import hi_eventGenerator from './hi/eventGenerator.json';
import hi_settings from './hi/settings.json';
import ja_ui from './ja/ui.json';
import ja_events from './ja/events.json';
import ja_social from './ja/social.json';
import ja_notifications from './ja/notifications.json';
import ja_extras from './ja/extras.json';
import ja_stages from './ja/stages.json';
import ja_rebirth from './ja/rebirth.json';
import ja_eventGenerator from './ja/eventGenerator.json';
import ja_settings from './ja/settings.json';

export const localeDictionaries: Record<Locale, Record<DictionaryName, any>> = {
  'en': {
    ui: en_ui,
    events: en_events,
    social: en_social,
    notifications: en_notifications,
    extras: en_extras,
    stages: en_stages,
    rebirth: en_rebirth,
    eventGenerator: en_eventGenerator,
    settings: en_settings,
  },
  'vi': {
    ui: vi_ui,
    events: vi_events,
    social: vi_social,
    notifications: vi_notifications,
    extras: vi_extras,
    stages: vi_stages,
    rebirth: vi_rebirth,
    eventGenerator: vi_eventGenerator,
    settings: vi_settings,
  },
  'id': {
    ui: id_ui,
    events: id_events,
    social: id_social,
    notifications: id_notifications,
    extras: id_extras,
    stages: id_stages,
    rebirth: id_rebirth,
    eventGenerator: id_eventGenerator,
    settings: id_settings,
  },
  'es': {
    ui: es_ui,
    events: es_events,
    social: es_social,
    notifications: es_notifications,
    extras: es_extras,
    stages: es_stages,
    rebirth: es_rebirth,
    eventGenerator: es_eventGenerator,
    settings: es_settings,
  },
  'it': {
    ui: it_ui,
    events: it_events,
    social: it_social,
    notifications: it_notifications,
    extras: it_extras,
    stages: it_stages,
    rebirth: it_rebirth,
    eventGenerator: it_eventGenerator,
    settings: it_settings,
  },
  'kk': {
    ui: kk_ui,
    events: kk_events,
    social: kk_social,
    notifications: kk_notifications,
    extras: kk_extras,
    stages: kk_stages,
    rebirth: kk_rebirth,
    eventGenerator: kk_eventGenerator,
    settings: kk_settings,
  },
  'zh-Hans': {
    ui: zh_Hans_ui,
    events: zh_Hans_events,
    social: zh_Hans_social,
    notifications: zh_Hans_notifications,
    extras: zh_Hans_extras,
    stages: zh_Hans_stages,
    rebirth: zh_Hans_rebirth,
    eventGenerator: zh_Hans_eventGenerator,
    settings: zh_Hans_settings,
  },
  'zh-Hant': {
    ui: zh_Hant_ui,
    events: zh_Hant_events,
    social: zh_Hant_social,
    notifications: zh_Hant_notifications,
    extras: zh_Hant_extras,
    stages: zh_Hant_stages,
    rebirth: zh_Hant_rebirth,
    eventGenerator: zh_Hant_eventGenerator,
    settings: zh_Hant_settings,
  },
  'ko': {
    ui: ko_ui,
    events: ko_events,
    social: ko_social,
    notifications: ko_notifications,
    extras: ko_extras,
    stages: ko_stages,
    rebirth: ko_rebirth,
    eventGenerator: ko_eventGenerator,
    settings: ko_settings,
  },
  'ms': {
    ui: ms_ui,
    events: ms_events,
    social: ms_social,
    notifications: ms_notifications,
    extras: ms_extras,
    stages: ms_stages,
    rebirth: ms_rebirth,
    eventGenerator: ms_eventGenerator,
    settings: ms_settings,
  },
  'de': {
    ui: de_ui,
    events: de_events,
    social: de_social,
    notifications: de_notifications,
    extras: de_extras,
    stages: de_stages,
    rebirth: de_rebirth,
    eventGenerator: de_eventGenerator,
    settings: de_settings,
  },
  'pl': {
    ui: pl_ui,
    events: pl_events,
    social: pl_social,
    notifications: pl_notifications,
    extras: pl_extras,
    stages: pl_stages,
    rebirth: pl_rebirth,
    eventGenerator: pl_eventGenerator,
    settings: pl_settings,
  },
  'pt': {
    ui: pt_ui,
    events: pt_events,
    social: pt_social,
    notifications: pt_notifications,
    extras: pt_extras,
    stages: pt_stages,
    rebirth: pt_rebirth,
    eventGenerator: pt_eventGenerator,
    settings: pt_settings,
  },
  'ro': {
    ui: ro_ui,
    events: ro_events,
    social: ro_social,
    notifications: ro_notifications,
    extras: ro_extras,
    stages: ro_stages,
    rebirth: ro_rebirth,
    eventGenerator: ro_eventGenerator,
    settings: ro_settings,
  },
  'ru': {
    ui: ru_ui,
    events: ru_events,
    social: ru_social,
    notifications: ru_notifications,
    extras: ru_extras,
    stages: ru_stages,
    rebirth: ru_rebirth,
    eventGenerator: ru_eventGenerator,
    settings: ru_settings,
  },
  'sw': {
    ui: sw_ui,
    events: sw_events,
    social: sw_social,
    notifications: sw_notifications,
    extras: sw_extras,
    stages: sw_stages,
    rebirth: sw_rebirth,
    eventGenerator: sw_eventGenerator,
    settings: sw_settings,
  },
  'th': {
    ui: th_ui,
    events: th_events,
    social: th_social,
    notifications: th_notifications,
    extras: th_extras,
    stages: th_stages,
    rebirth: th_rebirth,
    eventGenerator: th_eventGenerator,
    settings: th_settings,
  },
  'tr': {
    ui: tr_ui,
    events: tr_events,
    social: tr_social,
    notifications: tr_notifications,
    extras: tr_extras,
    stages: tr_stages,
    rebirth: tr_rebirth,
    eventGenerator: tr_eventGenerator,
    settings: tr_settings,
  },
  'fil': {
    ui: fil_ui,
    events: fil_events,
    social: fil_social,
    notifications: fil_notifications,
    extras: fil_extras,
    stages: fil_stages,
    rebirth: fil_rebirth,
    eventGenerator: fil_eventGenerator,
    settings: fil_settings,
  },
  'fr': {
    ui: fr_ui,
    events: fr_events,
    social: fr_social,
    notifications: fr_notifications,
    extras: fr_extras,
    stages: fr_stages,
    rebirth: fr_rebirth,
    eventGenerator: fr_eventGenerator,
    settings: fr_settings,
  },
  'hi': {
    ui: hi_ui,
    events: hi_events,
    social: hi_social,
    notifications: hi_notifications,
    extras: hi_extras,
    stages: hi_stages,
    rebirth: hi_rebirth,
    eventGenerator: hi_eventGenerator,
    settings: hi_settings,
  },
  'ja': {
    ui: ja_ui,
    events: ja_events,
    social: ja_social,
    notifications: ja_notifications,
    extras: ja_extras,
    stages: ja_stages,
    rebirth: ja_rebirth,
    eventGenerator: ja_eventGenerator,
    settings: ja_settings,
  },
};
