import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const localesRoot = path.join(__dirname, '..', 'src', 'locales');

const locales = [
  'en',
  'vi',
  'id',
  'es',
  'it',
  'kk',
  'zh-Hans',
  'zh-Hant',
  'ko',
  'ms',
  'de',
  'pl',
  'pt',
  'ro',
  'ru',
  'sw',
  'th',
  'tr',
  'fil',
  'fr',
  'hi',
  'ja',
];

const dictionaries = [
  'ui',
  'events',
  'social',
  'notifications',
  'extras',
  'stages',
  'rebirth',
  'eventGenerator',
  'settings',
];

const templates = {
  ui: {},
  events: {
    mundane: [],
    secret: [],
  },
  social: {},
  notifications: {},
  extras: {},
  stages: {},
  rebirth: {},
  eventGenerator: {},
  settings: {},
};

const ensureDirectory = (directoryPath) => {
  fs.mkdirSync(directoryPath, { recursive: true });
};

const writeJsonIfMissing = (filePath, content) => {
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n', 'utf8');
    console.log('Created:', path.relative(localesRoot, filePath));
  }
};

locales.forEach((locale) => {
  const localeDirectory = path.join(localesRoot, locale);
  ensureDirectory(localeDirectory);

  dictionaries.forEach((dictionary) => {
    const filePath = path.join(localeDirectory, dictionary + '.json');
    writeJsonIfMissing(filePath, templates[dictionary]);
  });
});

const safeVariableName = (locale, dictionary) => {
  return locale.replace(/-/g, '_').replace(/[^a-zA-Z0-9_]/g, '') + '_' + dictionary;
};

const importLines = [];
const localeBlocks = [];

locales.forEach((locale) => {
  const entries = [];

  dictionaries.forEach((dictionary) => {
    const variableName = safeVariableName(locale, dictionary);
    importLines.push('import ' + variableName + " from './" + locale + '/' + dictionary + ".json';");
    entries.push('    ' + dictionary + ': ' + variableName + ',');
  });

  localeBlocks.push("  '" + locale + "': {\n" + entries.join('\n') + '\n  },');
});

const indexContent = '/* Auto-generated by scripts/generateLocaleStubs.mjs. Do not edit manually. */\n' +
'import type { Locale } from \'../types\';\n\n' +
'export type DictionaryName =\n' +
'  | \'ui\'\n' +
'  | \'events\'\n' +
'  | \'social\'\n' +
'  | \'notifications\'\n' +
'  | \'extras\'\n' +
'  | \'stages\'\n' +
'  | \'rebirth\'\n' +
'  | \'eventGenerator\'\n' +
'  | \'settings\';\n\n' +
importLines.join('\n') + '\n\n' +
'export const localeDictionaries: Record<Locale, Record<DictionaryName, any>> = {\n' +
localeBlocks.join('\n') + '\n' +
'};\n';

fs.writeFileSync(path.join(localesRoot, 'index.ts'), indexContent, 'utf8');

console.log('Locale stubs and locale registry generated successfully.');